version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      - CCBMK2_CONFIG=production
    ports:
      - "1801:80"
    volumes:
      - ./web:/app
    depends_on:
      - db
    restart: on-failure
  optimisation:
    build:
      context: .
      dockerfile: ./optimisation/Dockerfile
    environment:
      - PYTHONUNBUFFERED=0
      - OPT_PROCS=6
    volumes:
      - ./optimisation:/app
    depends_on:
      - db
  db:
    image: mongo
