version: '2'
services:
  ccbuilder2-web:
    build:
      context: ./ccbuilder2/
      dockerfile: ./web/Dockerfile
    environment:
      - CCBMK2_CONFIG=production
    # ports:
    #   - "1801:80"
    # volumes:
    #   - ./web:/app
    depends_on:
      - ccbuilder2-db
    restart: on-failure
  # ccbuilder2-optimisation:
  #   build:
  #     context: ./ccbuilder2/
  #     dockerfile: ./optimisation/Dockerfile
  #   environment:
  #     - PYTHONUNBUFFERED=0
  #     - OPT_PROCS=6
  #   volumes:
  #     - ./optimisation:/app
  #   depends_on:
  #     - ccbuilder2-db
  ccbuilder2-db:
    image: mongo
